### ISSUE TITLE
Upgrade to new Moodle versions

### ISSUE THREAD

**Issue by taraghi** [emeneo/moodle-local_course_templates#13]
Hi,

Is there any plan to keep this plugin updated to current supported Moodle versions 3.9, 3.8?

Thanks
Beni

**Comment by gengoac** [comment]
Or 3.10... has development stopped? I signed up to Emeneo to see if there was anything new there but it only lists up to 3.5. Seems like there is still a need and desire for this plugin.

**Comment by pete1854** [comment]
Or 3.11+...

**Comment by taraghi** [comment]
@andrewscaya 
According to the Moodle plugin directory, the plugin provides still no support for Moodle 4.x:

https://moodle.org/plugins/local_course_templates/versions

Is that true?

**Comment by andrewscaya** [comment]
Hi @taraghi --

The last time I tested it, Course Templates was working fine on Moodle 4.0+. Let me do a few tests, and I'll get back to you shortly in order to confirm this.

@Flottertotte Hi! :) Nice to hear from this excellent project again! How are you doing? If this is fine with you, I'll run a few tests, and I'll get back to you maybe tomorrow?

**Comment by andrewscaya** [comment]
@Flottertotte I've checked my last tests, and Course Templates should work on Moodle 4.0+. If it is not the case, please let me know, and I'll have a look into it.

@taraghi From what I can see, you are good to go. If you encounter any issues, please open new issues for easier tracking of any potential progress.

Have a great weekend!

Best,

Andrew

**Comment by taraghi** [comment]
@andrewscaya  great news indeed. Thanks a lot.

Nevertheless it is a pity that the information on moodle plugin directory is not up to date. Thus the community assumes that the plugin is not Moodle 4 compatible and does not use the plugin although it is actually a great plugin.

I wish you a great weekend too.

Best,
Beni

**Comment by Flottertotte** [comment]
Hi @taraghi, @andrewscaya and @onword  

Sorry and thanks a lot for your efforts. The plugin has now been published for 4.x

The problem was on our side: we thought there is still a problem (related to deleted categories). But this problem had been fixed already and we thought we published and updated 3.11 version on moodle.org (but in fact we forgot to do so) . As we later on, kept receiving reports about this problem, we thought it actually still hasn't been fixed and therefore kept the plugin on 3.11

Hope now many will enjoy the plugin also on 4.x

Thanks again and all the best!
