### ISSUE TITLE
Moodle 3.8

### ISSUE THREAD

**Issue by frumbert** [emeneo/moodle-local_course_templates#23]
According to the page https://moodle.org/plugins/local_course_templates the plugin supports 3.7 and 3.8; however, it relies on the function _require_all_capabilities(...)_ which was not implemented into accesslib.php until 3.9. Not hard to patch back in, but out of the box it doesn't work < 3.9

**Comment by Flottertotte** [comment]
Thank you @frumbert , I have already changed the min. version requirement to 3.9 and reopened the older version. In there is someone who is running moodle 3.7. and cannot upgrade and installated the new plugin version that does not run on 3.7. might fix version number so that they can downgrade back. Hope there aren't such cases thanks to your fast warning!

Best,
Flotter

**Comment by andrewscaya** [comment]
@Flottertotte 

Would like for us to have a look, and backport the latest changes to Moodle 3.7 and 3.8?

**Comment by Flottertotte** [comment]
Hi @andrewscaya, that would be awesome, of course. I would then pack new version based on that work and publish update the old package on moodle.org

**Comment by Flottertotte** [comment]
@andrewscaya I have created a 3.7 branch.

**Comment by andrewscaya** [comment]
Hi @Flottertotte --

OK. I'll have the PR ready before the end of the day. 👍

**Comment by andrewscaya** [comment]
@Flottertotte 

I have a question for you: do you prefer maintaining two separate branches, or do you want me to simply add a shim in the master branch that will make the main release compatible with 3.X?

**Comment by Flottertotte** [comment]
@andrewscaya If feel it is easier to handle with 2 separate branches.

**Comment by andrewscaya** [comment]
@Flottertotte --

Since the 3.7 branch was not available on the public repository, I issued the PR #24 against the master branch. Thus, you can still choose to either have one single version that is compatible with Moodle 3.6+ (simply merge on master), or create a separate branch with this added shim (another branch).

If you decide to create a separate version for 3.6+, I would recommend that you update the main version.php file to require Moodle 3.9+ (2020061500).

If you have any questions or comments, please let me know, ok?

TTYL! :)

Yours,

Andrew

**Comment by Flottertotte** [comment]
@andrewscaya Thank you! I will look into it asap and follow up.

**Comment by Flottertotte** [comment]
@andrewscaya Thanks again! I just merged to master and published a new release to moodle.org Best, Flotter
